version: '3'

services:
  api:
    image: pastebim:latest
    restart: always
    network_mode: "host"
    volumes:
      - ~/pastes:/pastes
    ports:
      - "6969:6969"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
